header_font = (None, 20)
text_font = (None, 12)
small_text_font = (None, 10)
entry_font = (None, 12)
small_entry_font = (None, 10)
radiobutton_font = (None, 12)
button_font = (None, 12)
checkbutton_font = (None, 12)